# Generated by Django 6.1 on 2026-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='new', max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('medium', 'Medium'), ('high', 'High'), ('very high', 'Very  High')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
