# Generated by Django 6.1.1 on 2026-09-20 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='base.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='priority',
            field=models.CharField(blank=True, choices=[('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomerFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_folders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='base.customers')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='base.customerfolder'),
        ),
        migrations.AddConstraint(
            model_name='customerfolder',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_folder_per_customer'),
        ),
    ]
