# Generated by Django 6.1 on 2026-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_billingdocument_billingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
